server:
  port: 9020

spring:
  application:
    name: msvc-support
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5436/postgres
    #username: support
    #password: 1234
    #Producción
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://srv1455.hstgr.io:3306/u854419727_support
    username: u854419727_auxi_support
    password: 8Qi1bSH!
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
    #hostname: eureka-microservice-0
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka
