apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: danielchaparro/gateway-microservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice-svc
spec:
  type: LoadBalancer
  selector:
    app: gateway-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
