apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-microservice
  template:
    metadata:
      labels:
        app: eureka-microservice
    spec:
      containers:
        - name: eureka-microservice
          image: danielchaparro/eureka-microservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-microservice-svc
spec:
  selector:
    app: eureka-microservice
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
