version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=profile
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - ~/docker/postgres-data:/var/lib/postgres