server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
        - id: profile-service
          uri: http://localhost:9000
          predicates:
            - Path=/experience/**
            - Path=/profile/**
            - Path=/studies/**
          filters:
            - AuthFilter