server:
  port: 9010

spring:
  application:
    name: msvc-offer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: offer
    password: 1234
    #Producción
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    #username: postgres.uusgbsnxvzltkoxnglpz
    #password: Rjj7riruAd7pAcVU
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
    #hostname: eureka-microservice-0
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka