server:
  port: 9000

spring:
  application:
    name: msvc-profile
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: profile
    password: 1234
    #Producción
    #url: jdbc:postgresql://db.zvjhhksmluxartprywva.supabase.co:5432/postgres
    #username: postgres
    #password: gbRRwSWdsmo5JNhR
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
