version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      #MYSQL_ROOT_PASSWORD: bF1E3e3fH-2DADF366C626-fFEGbfeGb
      #MYSQL_DATABASE: railway
      #MYSQL_USER: root
      #MYSQL_PASSWORD: bF1E3e3fH-2DADF366C626-fFEGbfeGb
    ports:
      - '3306:3306'
      #- '3306:58894'

