server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
    #hostname: "${HOSTNAME}.eureka"
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://localhost:${server.port}/eureka/

