server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:${server.port}/eureka/
